name: detr 

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - numpy<2
  - scipy
  - scipy-stubs
  - scikit-learn
  - pandas
  - pillow
  - matplotlib
  - pycocotools
  - accelerate
  - transformers
  - timm
  - wandb
  - pytest
  - ipykernel
  - black
  - isort
  
  - pip:
    - torch
    - torchvision
    - --index-url https://download.pytorch.org/whl/cu126