name: detr 

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - numpy<2
  - libstdcxx-ng
  - scipy
  - scipy-stubs
  - scikit-learn
  - pandas
  - pillow
  - matplotlib
  - pycocotools
  - accelerate
  - nvidia-ml-py
  - transformers
  - timm
  - wandb
  - hydra-core
  - ipykernel
  - ipywidgets
  - ruff
  - black
  - pytest
  - pre-commit
  - nvtop
  - htop
  
  - pip:
    - torch
    - torchvision
    - --index-url https://download.pytorch.org/whl/cu126