pretrained_weights: Null

embed_dim: 256

backbone:
  name: convnext_tiny
  embed_dim: ${model.embed_dim}
  num_levels: 2
  pretrained: True

encoder:
  num_layers: 6
  embed_dim: ${model.embed_dim}
  layer:
    _target_: models.encoder.DeformableEncoderLayer
    embed_dim: ${model.embed_dim}
    ffn_dim: 2048
    num_heads: 8
    num_levels: ${model.backbone.num_levels}
    num_points: 5
    dropout: 0.1

decoder:
  num_layers: 6
  embed_dim: ${model.embed_dim}
  num_queries: 100
  return_intermediates: True
  layer:
    _target_: models.decoder.DecoderLayer
    embed_dim: ${model.embed_dim}
    ffn_dim: ${model.encoder.layer.ffn_dim}
    num_heads: ${model.encoder.layer.num_heads}
    dropout: ${model.encoder.layer.dropout}
