train:
  _target_: data.transforms.make_transformations
  split: train
  resolution: 480

val:
  _target_: data.transforms.make_transformations
  split: val 
  resolution: 480

test:
  _target_: data.transforms.make_transformations
  split: test
  resolution: 480