defaults:
  - hydra: simple
  - dataset: coco
  - transforms: nano
  - model: detr
  - optimizer: adamw
  - scheduler: step
  - criterion: detr
  - _self_

train:
  output_dir: /data/troy/models/detr/detr-nano
  num_epochs: 300
  batch_size: 64
  num_workers: 6
  save_period: 5
  max_grad_norm: 0.1
  checkpoint: Null