defaults:
  - hydra: simple
  - dataset: coco
  - transforms: nano
  - model: detr 
  - optimizer: detr 
  - scheduler: detr 
  - criterion: detr
  - _self_

train:
  output_dir: /path/to/output/dir
  num_epochs: 500
  batch_size: 64
  num_workers: 4
  save_period: 10
  max_grad_norm: 0.1
  random_seed: 42
  checkpoint: Null
