defaults:
  - hydra: simple
  - dataset: coco
  - transforms: nano
  - model: dino
  - optimizer: dino 
  - scheduler: dino
  - criterion: dino 
  - _self_

train:
  output_dir: /path/to/output/dir
  num_epochs: 12 
  batch_size: 8
  num_workers: 6
  save_period: 10
  max_grad_norm: 0.1
  random_seed: 42
  checkpoint: Null